#!/bin/bash

# Load Testing Script
# Runs k6 load tests and generates performance reports

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
API_URL=${API_URL:-"http://localhost:3001/api/v1"}
TEST_USER_EMAIL=${TEST_USER_EMAIL:-"loadtest@example.com"}
TEST_USER_PASSWORD=${TEST_USER_PASSWORD:-"LoadTest123!"}
RESULTS_DIR="./load-test-results"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Check if k6 is installed
if ! command -v k6 &> /dev/null; then
    echo -e "${RED}Error: k6 is not installed${NC}"
    echo "Install k6: https://k6.io/docs/getting-started/installation/"
    exit 1
fi

# Create results directory
mkdir -p "$RESULTS_DIR"

echo -e "${GREEN}Starting Load Tests...${NC}"
echo "API URL: $API_URL"
echo "Test User: $TEST_USER_EMAIL"
echo "Results Directory: $RESULTS_DIR"
echo ""

# Function to run a test
run_test() {
    local test_name=$1
    local test_file=$2
    
    echo -e "${YELLOW}Running: $test_name${NC}"
    
    export API_URL=$API_URL
    export TEST_USER_EMAIL=$TEST_USER_EMAIL
    export TEST_USER_PASSWORD=$TEST_USER_PASSWORD
    
    k6 run \
        --out json="$RESULTS_DIR/${test_name}_${TIMESTAMP}.json" \
        --out csv="$RESULTS_DIR/${test_name}_${TIMESTAMP}.csv" \
        "$test_file" \
        > "$RESULTS_DIR/${test_name}_${TIMESTAMP}.log" 2>&1
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ $test_name completed successfully${NC}"
    else
        echo -e "${RED}✗ $test_name failed${NC}"
        echo "Check logs: $RESULTS_DIR/${test_name}_${TIMESTAMP}.log"
    fi
    echo ""
}

# Run all tests
echo -e "${GREEN}=== Running API Endpoints Test ===${NC}"
run_test "api-endpoints" "api-endpoints.test.js"

echo -e "${GREEN}=== Running Database Performance Test ===${NC}"
run_test "database-performance" "database-performance.test.js"

echo -e "${GREEN}=== Running File Upload/Download Test ===${NC}"
run_test "file-operations" "file-upload-download.test.js"

echo -e "${GREEN}=== Running Full Load Test ===${NC}"
run_test "full-load" "full-load.test.js"

# Generate summary report
echo -e "${GREEN}Generating Summary Report...${NC}"
cat > "$RESULTS_DIR/summary_${TIMESTAMP}.md" << EOF
# Load Test Summary Report

**Generated:** $(date)

## Test Configuration
- API URL: $API_URL
- Test User: $TEST_USER_EMAIL
- Timestamp: $TIMESTAMP

## Tests Run
1. API Endpoints Test
2. Database Performance Test
3. File Upload/Download Test
4. Full Load Test

## Results Location
All results are in: \`$RESULTS_DIR\`

### Files Generated
- JSON results: \`*_${TIMESTAMP}.json\`
- CSV results: \`*_${TIMESTAMP}.csv\`
- Logs: \`*_${TIMESTAMP}.log\`
- HTML reports: \`*_${TIMESTAMP}.html\` (if generated by tests)

## Next Steps
1. Review the JSON/CSV files for detailed metrics
2. Check HTML reports for visual summaries
3. Analyze logs for any errors or warnings
4. Compare results across different test runs
EOF

echo -e "${GREEN}✓ All tests completed!${NC}"
echo -e "Results saved to: ${YELLOW}$RESULTS_DIR${NC}"
echo -e "Summary report: ${YELLOW}$RESULTS_DIR/summary_${TIMESTAMP}.md${NC}"

